accounts/urls.py
from django.urls import path
from accounts import views 
from django.contrib.auth.views import LogoutView
from django.urls import path, re_path
from django.views.generic import TemplateView



app_name = 'accounts'

urlpatterns = [
    path('login/',views.login, name='login'),
    path('logout/',LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('informacion_pagina', views.inicio, name='informacion_pagina'),
    path('registro/',views.registrarse, name='registrarse'),
    path('perfil/editar/', views.edicion_perfil, name='edicion_perfil'),
    path('perfil/editar/password', views.ModificarPass.as_view(), name='modificar_pass'),
]
    
urlpatterns += [
    re_path(r'^.*$', TemplateView.as_view(template_name='accounts/errores_ruta.html'), name='errores_ruta'),
]

inicio/urls.py
from django.urls import path
from .views import BookListView, BookDetailView, BookUpdateView, BookDeleteView ,BookCreateView , InicioView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


app_name = 'inicio'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', InicioView.as_view(), name='inicio'),
    path('listar_libros/', BookListView.as_view(), name='book_list'),
    path('create/', BookCreateView.as_view(), name='book_create'),
    path('<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('<int:pk>/update/', BookUpdateView.as_view(), name='book_update'),
    path('<int:pk>/delete/', BookDeleteView.as_view(), name='book_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectofinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('', include('inicio.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tercer_preentrega/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('', include('inicio.urls')),
    path('admin/', admin.site.urls),
    
    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class InfoExtra(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True) 

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm


class MiFormularioDeCreacionDeUsuarios(UserCreationForm):
    first_name=forms.CharField(label='Nombre',max_length=20)
    last_name =forms.CharField(label='Apellido',max_length=20)
    email = forms.EmailField()
    password1 = forms.CharField(label='Contrasenia', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir Contrasenia', widget=forms.PasswordInput)
    descripcion = forms.CharField(label='Descripcion',max_length=50)
    link = forms.CharField(label='Ruta',max_length=50)
    avatar = forms.ImageField(required=False) 
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name','descripcion','link','avatar']
        help_texts = {k:"" for k in fields}
        
class MiFormularioDeEdicionDeDatosDelUsuario(UserChangeForm):
    password=None
    email = forms.EmailField()
    first_name = forms.CharField(label='Nombre',max_length=20)
    last_name = forms.CharField(label='Apellido',max_length=20)
    descripcion = forms.CharField(label='Descripcion',max_length=50)
    link = forms.CharField(label='Ruta',max_length=50)
    avatar = forms.ImageField(required=False)
    
    class Meta():
        model=User
        fields=['email','first_name','last_name','descripcion','link','avatar']

accounts/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login as django_login
from django.contrib.auth.decorators import login_required
from django.views import View
from accounts.forms import MiFormularioDeCreacionDeUsuarios, MiFormularioDeEdicionDeDatosDelUsuario
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from accounts.models import InfoExtra


def login(request):
    
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            usuario = formulario.cleaned_data['username']
            contrasenia = formulario.cleaned_data['password']
            
            
            user = authenticate(username=usuario, password=contrasenia)
            
            django_login(request, user)
            
            InfoExtra.objects.get_or_create(user=user)
            
            return redirect('inicio:inicio')
        else:
            return render(request, 'accounts/login.html', {'formulario':formulario})
    
    formulario = AuthenticationForm()
    return render(request, 'accounts/login.html', {'formulario':formulario})


def registrarse(request):
    if request.method == 'POST':
        formulario =MiFormularioDeCreacionDeUsuarios(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect ('accounts:login')
        else:
            return render(request , 'accounts/registro.html', {'formulario':formulario})
    
    formulario = MiFormularioDeCreacionDeUsuarios()
    return render(request , 'accounts/registro.html', {'formulario':formulario})

@login_required
def edicion_perfil(request):
    info_extra_user = request.user.infoextra
    if request.method == 'POST':
        formulario = MiFormularioDeEdicionDeDatosDelUsuario(request.POST, request.FILES,instance=request.user)
        if formulario.is_valid():
            
            avatar = formulario.cleaned_data.get('avatar')
            if avatar:
                info_extra_user.avatar = avatar
                info_extra_user.save()
            
            formulario.save()
            return redirect('inicio:inicio')
    else:
        formulario = MiFormularioDeEdicionDeDatosDelUsuario(initial={'avatar':info_extra_user.avatar},instance=request.user)
        
    return render (request, 'accounts/edicion_perfil.html',{'formulario': formulario})
    
class ModificarPass(LoginRequiredMixin, PasswordChangeView):
    template_name = 'accounts/modificar_pass.html'
    success_url = reverse_lazy('accounts:edicion_perfil')
    
def inicio(request):
    contexto = {
        'mensaje': ''
    }
    return render(request, 'accounts/informacion_pagina.html', contexto)

accounts/templates/accounts/edicion_perfil.html
{% extends 'base.html' %}

{% load static %}

{% block title %}<title>Edicion Perfil</title>{% endblock %}

{% block heading %}¡Editar Perfil!{% endblock %}

{% block content %}
<form action={% url 'accounts:edicion_perfil' %} method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Guardar Cambios</button>
    <button type='button'><a class='navbar-brand' href={% url 'accounts:modificar_pass' %}> Cambiar Clave</a></button>
</form>
{% endblock content %}

accounts/templates/accounts/errores_ruta.html
{% extends 'base.html' %}

{% load static %}

{% block title %}<title>No existe la pagina</title>{% endblock %}

{% block heading %}
    <h1>Error: No hay paginas aun</h1>
    <p>Lo sentimos, la página que estás buscando no existe.</p>
{% endblock %}

{% block content %}
{% endblock content %}

accounts/templates/accounts/informacion_pagina.html
{% extends 'base.html' %}

{% load static %}

{% block title %}<title>Nuestra pagina</title>{% endblock %}

{% block heading %}
    <h1>Informacion de la pagina</h1>
{% endblock %}

{% block content %}
    <form action={% url 'accounts:informacion_pagina' %} method="POST">
        {% csrf_token %}
        <p class='informacion' style="color: blue; font-family: 'Comic Sans MS', sans-serif;font-size: 20px;">
           Esta es la informacion de nuestra pagina hecha por Nicolas Gabriel Gonzalez y Ezequiel Pizzo Montgomery.<br>
           Nicolas Goznzalez: Empleado en soporte tecnico, busco nuevos aprendizajes, y mas desarrollos en la tecnologia.<br>
           Ezequiel Pizzo Montgomery: Empleado en pasteleria, desarrollar nuestra actividad/proyecto y mejorar las tecnicas en informatica.<br>
           Para este proyecto se diseño una pagina en la que cada usuario pueda cargar, ver y cambiar y eliminar libros para su compra y venta simpre y cuando tenga su usario logueado. <br>
           En esta pagina se utilizaron django, sql, html, css y librerias.
        </p>
    </form>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %}<title>Login</title>{% endblock %}

{% block heading %}¡Login!{% endblock %}

{% block content %}
<form action={% url 'accounts:login' %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Login</button>
</form>
{% endblock content %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% load static %}

{% block title %}<title>Logout</title>{% endblock %}

{% block heading %}¡Te deslogeaste con exito!{% endblock %}

{% block content %}
{% endblock content %}

accounts/templates/accounts/modificar_pass.html
{% extends 'base.html' %}

{% load static %}

{% block title %}<title>Modificar Pass</title>{% endblock %}

{% block heading %}¡Modificar Contraseña!{% endblock %}

{% block content %}
<form action={% url 'accounts:modificar_pass' %} method="POST" >
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Guardar Cambios</button>
</form>
{% endblock content %}

accounts/templates/accounts/perfil.html
{% extends 'base.html' %}

{% block title %}
<title>Editar perfil</title>
{% endblock title %}

{% block heading %}
Editar perfil
{% endblock heading %}

{% block content %}
<form action="{% url 'accounts:editar_perfil' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_table }}
</form>
{% endblock content %}

accounts/templates/accounts/registro.html
{% extends 'base.html' %}

{% load static %}

{% block title %}<title>Registrarse</title>{% endblock %}

{% block heading %}¡Registro!{% endblock %}

{% block content %}
<form action={% url 'accounts:registrarse' %} method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Registrar</button>
</form>
{% endblock content %}