accounts/urls.py
from django.urls import path
from accounts import views 
from django.contrib.auth.views import LogoutView
from django.urls import path, re_path
from django.views.generic import TemplateView



app_name = 'accounts'

urlpatterns = [
    path('login/',views.login, name='login'),
    path('logout/',LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('informacion_pagina', views.inicio, name='informacion_pagina'),
    path('registro/',views.registrarse, name='registrarse'),
    path('perfil/editar/', views.edicion_perfil, name='edicion_perfil'),
    path('perfil/editar/password', views.ModificarPass.as_view(), name='modificar_pass'),
]
    
urlpatterns += [
    re_path(r'^.*$', TemplateView.as_view(template_name='accounts/errores_ruta.html'), name='errores_ruta'),
]

inicio/urls.py
from django.urls import path
from .views import BookListView, BookDetailView, BookUpdateView, BookDeleteView ,BookCreateView , InicioView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


app_name = 'inicio'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', InicioView.as_view(), name='inicio'),
    path('listar_libros/', BookListView.as_view(), name='book_list'),
    path('create/', BookCreateView.as_view(), name='book_create'),
    path('<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('<int:pk>/update/', BookUpdateView.as_view(), name='book_update'),
    path('<int:pk>/delete/', BookDeleteView.as_view(), name='book_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectofinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('', include('inicio.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tercer_preentrega/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('', include('inicio.urls')),
    path('admin/', admin.site.urls),
    
    ]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title %}
        {% endblock title %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />

    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="btn btn-primary" href="{% url 'inicio:book_list' %}" >Lista de Libros</a>
                <a class="btn btn-primary" href="{% url 'inicio:book_create' %}">Crear Libro</a>
                <a class="btn btn-primary" href="{% url 'accounts:informacion_pagina' %}">Acerca de Mi</a>
                {% if request.user.is_authenticated %}
                {% if request.user.infoextra.avatar %}
                <Img src={{request.user.infoextra.avatar.url}} alt=""height=='40px'>
                {% endif %}
                <a class="btn btn-secondary" href="{% url 'accounts:edicion_perfil' %}">{{request.user.username}}</a>
                <a class="btn btn-secondary" href="{% url 'accounts:logout' %}">Logout</a>
                {% else %}
                <a class="btn btn-primary" href="{% url 'accounts:login' %}">Login</a>
                <a class="btn btn-primary" href="{% url 'accounts:registrarse' %}">Registrarse</a>
                {% endif %}
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">
                                {% block heading %}
                                {% endblock heading %}
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% block content %}
        {% endblock content %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Tu Sitio Web 2023. Todos los derechos reservados.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>